theme: jekyll-theme-minimal

# Site settings
title: PR Size Enforcer
description: Automatically close pull requests that exceed a configurable size threshold.
baseurl: "/pr-size-enforcer/" # the subpath of your site, e.g. /blog
url: "https://jeremyrms.github.io" # the base hostname & protocol for your site

# Author settings
author:
  name: Jeremy Lamit
  email: jeremy.lamit@gmail.com
